version: "3.8"
services:
  # Backend service
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  # Frontend service
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    env_file:
      - .env
