FROM node:18-alpine

WORKDIR /app

COPY client/package*.json ./

# Remove existing node_modules if they exist
RUN rm -rf node_modules

RUN npm install

COPY client/ .

EXPOSE 5173

# Modified command to allow external connections
CMD ["npm", "run", "dev"]